#=============================================================================================
# Project name: test6_1
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2026/03/01 1:56:49
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
i0001 = 0
i0002 = 0
i0003 = 0
d0001 = 0
d0002 = 0
d0003 = 0
d0004 = 0
d0005 = 0
d0006 = 0
d0007 = 0
d0008 = 0
d0009 = 0
d0010 = 0
d0011 = 0
d0012 = 0
d0013 = 0
d0014 = 0
d0015 = 0
d0016 = 0
d0017 = 0
d1001 = numpy.array([])
d1001_size = numpy.array([-1])
d0001 = -10
d1001_size[0] = 10
d1001 = numpy.zeros(d1001_size[0])
for i0001 in range(0, d1001_size[0], 1):
  d1001[i0001] = i0001
for i0001 in range(0, d1001_size[0], 1):
  #代数微分
  d0007 = 0
  for i0002 in range(0, 10, 1):
    d0007 = d0007+i0002*i0002
  d0006 = d0007
  d0008 = 0
  for i0002 in range(0, 10, 1):
    if i0002 == i0001:
      i0003 = 1
    else:
      i0003 = 0
    d0008 = d0008+i0002*i0002*i0003
  d0009 = 0
  for i0002 in range(0, 10, 1):
    d0009 = d0009
  d0010 = 0
  for i0002 in range(0, 10, 1):
    d0010 = d0010+i0002*i0002*d1001[i0002]
  d0011 = 0
  for i0002 in range(0, 10, 1):
    d0011 = d0011
  d0004 = d0008/d0006+(d0009/d0006-d0010/d0006**2)*d0011
  #数値微分
  d0013 = 0
  for i0002 in range(0, 10, 1):
    d0013 = d0013+i0002*i0002
  d0012 = d0013
  d0014 = 0
  for i0002 in range(0, 10, 1):
    d0014 = d0014+i0002*i0002*d1001[i0002]
  d0002 = d0014/d0012
  d1001[i0001] = d1001[i0001]+1.0E-5
  d0016 = 0
  for i0002 in range(0, 10, 1):
    d0016 = d0016+i0002*i0002
  d0015 = d0016
  d0017 = 0
  for i0002 in range(0, 10, 1):
    d0017 = d0017+i0002*i0002*d1001[i0002]
  d0003 = d0017/d0015
  d1001[i0001] = d1001[i0001]-1.0E-5
  print("%8d%27.12e%27.12e" %(i0001,d0004,(d0003-d0002)/1.0E-5))
d1001_size[0] = -1
del d1001
