!=============================================================================================
! Project name: test6_1
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2026/03/01 1:56:48
!=============================================================================================
program test6_1
implicit none
integer :: i0001
integer :: i0002
integer :: i0003
double precision :: d0001
double precision :: d0002
double precision :: d0003
double precision :: d0004
double precision :: d0005
double precision :: d0006
double precision :: d0007
double precision :: d0008
double precision :: d0009
double precision :: d0010
double precision :: d0011
double precision :: d0012
double precision :: d0013
double precision :: d0014
double precision :: d0015
double precision :: d0016
double precision :: d0017
double precision,allocatable :: d1001(:)
integer :: d1001_size(1:1) = (/ -1 /)
d0001 = -10
d1001_size(1) = 10
allocate(d1001(1:d1001_size(1)))
do i0001=0,d1001_size(1)-1
  d1001(i0001+1) = i0001
end do
do i0001=0,d1001_size(1)-1
  !代数微分
  d0007 = 0
  do i0002=0,9
    d0007 = d0007+i0002*i0002
  end do
  d0006 = d0007
  d0008 = 0
  do i0002=0,9
    if(i0002+1 == i0001+1) then
      i0003 = 1
    else
      i0003 = 0
    endif
    d0008 = d0008+i0002*i0002*i0003
  end do
  d0009 = 0
  do i0002=0,9
    d0009 = d0009
  end do
  d0010 = 0
  do i0002=0,9
    d0010 = d0010+i0002*i0002*d1001(i0002+1)
  end do
  d0011 = 0
  do i0002=0,9
    d0011 = d0011
  end do
  d0004 = d0008/d0006+(d0009/d0006-d0010/d0006**2)*d0011
  !数値微分
  d0013 = 0
  do i0002=0,9
    d0013 = d0013+i0002*i0002
  end do
  d0012 = d0013
  d0014 = 0
  do i0002=0,9
    d0014 = d0014+i0002*i0002*d1001(i0002+1)
  end do
  d0002 = d0014/d0012
  d1001(i0001+1) = d1001(i0001+1)+1.0d-5
  d0016 = 0
  do i0002=0,9
    d0016 = d0016+i0002*i0002
  end do
  d0015 = d0016
  d0017 = 0
  do i0002=0,9
    d0017 = d0017+i0002*i0002*d1001(i0002+1)
  end do
  d0003 = d0017/d0015
  d1001(i0001+1) = d1001(i0001+1)-1.0d-5
  print *, i0001,d0004,(d0003-d0002)/1.0d-5
end do
d1001_size(1) = -1
deallocate(d1001)
contains
end program test6_1
