#=============================================================================================
# Project name: test6_2
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2026/03/01 4:06:00
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
import pyfftw
t0003 = 0
f0002 = 0
ftplan3 = numpy.zeros(8,dtype=int)
ftplan3_size = numpy.array([8])
ftplan2 = numpy.zeros(8,dtype=int)
ftplan2_size = numpy.array([8])
ftplan1 = numpy.zeros(8,dtype=int)
ftplan1_size = numpy.array([8])
t0002 = 0
f0001 = 0
byte_tmp = 0
t0001 = 0
f0000 = 0
i0001 = 0
i0002 = 0
i0003 = 0
i0004 = 0
i0005 = 0
i0006 = 0
i0007 = 0
i0008 = 0
z0001 = 0
z2001 = numpy.array([[]], dtype=int)
z2001_size = numpy.array([-1,-1])
z2002 = numpy.array([[]], dtype=int)
z2002_size = numpy.array([-1,-1])
z2001_size[0] = 101
z2001_size[1] = 101
z2001 = numpy.zeros(z2001_size[0]*z2001_size[1], dtype=numpy.complex128).reshape(int(z2001_size[0]),int(z2001_size[1]))
z2002_size[0] = 101
z2002_size[1] = 101
z2002 = numpy.zeros(z2002_size[0]*z2002_size[1], dtype=numpy.complex128).reshape(int(z2002_size[0]),int(z2002_size[1]))
z2001[:,:]=0
z2001[50,50] = 1
t0001= "f.dat"%()
f0000 = open(t0001,mode="w")
for i0001 in range(0, z2001_size[0], 1):
  for i0002 in range(0, z2001_size[1], 1):
    f0000.write("%8d\t%8d\t%27.12e\t%27.12e\n" %(i0001,i0002,(z2001[i0001,i0002]).real,(z2001[i0001,i0002]).imag))
f0000.close()
z2002[:,:]=0
z2002[50,50] = 1
t0002= "g.dat"%()
f0001 = open(t0002,mode="w")
for i0001 in range(0, z2002_size[0], 1):
  for i0002 in range(0, z2002_size[1], 1):
    f0001.write("%8d\t%8d\t%27.12e\t%27.12e\n" %(i0001,i0002,(z2002[i0001,i0002]).real,(z2002[i0001,i0002]).imag))
f0001.close()
i0001 = z2001_size[0]
i0002 = z2001_size[1]
i0003 = z2001_size[0]//2
i0004 = z2001_size[1]//2
z2001_empty = pyfftw.empty_aligned(z2001.shape, dtype='complex128')
ftplan1 = pyfftw.builders.fft2(z2001_empty)
if divmod(z2001_size[1],2) == 0:
  for i0005 in range(0, z2001_size[0], 1):
    for i0006 in range(0, z2001_size[1]//2, 1):
      z0001 = z2001[i0005,i0006+z2001_size[1]//2]
      z2001[i0005,i0006+z2001_size[1]//2] = z2001[i0005,i0006]
      z2001[i0005,i0006] = z0001
else:
  for i0005 in range(0, z2001_size[0], 1):
    i0006 = 0
    z0001 = z2001[i0005,i0006]
    for i0008 in range(0, z2001_size[1], 1):
      if i0006+z2001_size[1]//2+1 >= z2001_size[1]:
        i0007 = i0006+z2001_size[1]//2+1-z2001_size[1]
      else:
        i0007 = i0006+z2001_size[1]//2+1
      z2001[i0005,i0006] = z2001[i0005,i0007]
      i0006 = i0007
    z2001[i0005,i0006+z2001_size[1]//2+1-1] = z0001
if divmod(z2001_size[0],2) == 0:
  for i0005 in range(0, z2001_size[1], 1):
    for i0006 in range(0, z2001_size[0]//2, 1):
      z0001 = z2001[i0006+z2001_size[0]//2,i0005]
      z2001[i0006+z2001_size[0]//2,i0005] = z2001[i0006,i0005]
      z2001[i0006,i0005] = z0001
else:
  for i0005 in range(0, z2001_size[1], 1):
    i0006 = 0
    z0001 = z2001[i0006,i0005]
    for i0008 in range(0, z2001_size[0], 1):
      if i0006+z2001_size[0]//2+1 >= z2001_size[0]:
        i0007 = i0006+z2001_size[0]//2+1-z2001_size[0]
      else:
        i0007 = i0006+z2001_size[0]//2+1
      z2001[i0006,i0005] = z2001[i0007,i0005]
      i0006 = i0007
    z2001[i0006+z2001_size[0]//2+1-1,i0005] = z0001
z2001_empty[:] = z2001[:]
#FFTを実行
z2001 = ftplan1()
if divmod(z2001_size[1],2) == 0:
  for i0005 in range(0, z2001_size[0], 1):
    for i0006 in range(0, z2001_size[1]//2, 1):
      z0001 = z2001[i0005,i0006+z2001_size[1]//2]
      z2001[i0005,i0006+z2001_size[1]//2] = z2001[i0005,i0006]
      z2001[i0005,i0006] = z0001
else:
  for i0005 in range(0, z2001_size[0], 1):
    i0006 = 0
    z0001 = z2001[i0005,i0006]
    for i0008 in range(0, z2001_size[1], 1):
      if i0006+z2001_size[1]//2+1 >= z2001_size[1]:
        i0007 = i0006+z2001_size[1]//2+1-z2001_size[1]
      else:
        i0007 = i0006+z2001_size[1]//2+1
      z2001[i0005,i0006] = z2001[i0005,i0007]
      i0006 = i0007
    z2001[i0005,i0006+z2001_size[1]//2+1-1] = z0001
if divmod(z2001_size[0],2) == 0:
  for i0005 in range(0, z2001_size[1], 1):
    for i0006 in range(0, z2001_size[0]//2, 1):
      z0001 = z2001[i0006+z2001_size[0]//2,i0005]
      z2001[i0006+z2001_size[0]//2,i0005] = z2001[i0006,i0005]
      z2001[i0006,i0005] = z0001
else:
  for i0005 in range(0, z2001_size[1], 1):
    i0006 = 0
    z0001 = z2001[i0006,i0005]
    for i0008 in range(0, z2001_size[0], 1):
      if i0006+z2001_size[0]//2+1 >= z2001_size[0]:
        i0007 = i0006+z2001_size[0]//2+1-z2001_size[0]
      else:
        i0007 = i0006+z2001_size[0]//2+1
      z2001[i0006,i0005] = z2001[i0007,i0005]
      i0006 = i0007
    z2001[i0006+z2001_size[0]//2+1-1,i0005] = z0001
del ftplan1
#規格化
for i0005 in range(0, i0001, 1):
  for i0006 in range(0, i0002, 1):
    z2001[i0005,i0006] = z2001[i0005,i0006]/(i0001*i0002)
i0001 = z2002_size[0]
i0002 = z2002_size[1]
i0003 = z2002_size[0]//2
i0004 = z2002_size[1]//2
z2002_empty = pyfftw.empty_aligned(z2002.shape, dtype='complex128')
ftplan2 = pyfftw.builders.fft2(z2002_empty)
if divmod(z2002_size[1],2) == 0:
  for i0005 in range(0, z2002_size[0], 1):
    for i0006 in range(0, z2002_size[1]//2, 1):
      z0001 = z2002[i0005,i0006+z2002_size[1]//2]
      z2002[i0005,i0006+z2002_size[1]//2] = z2002[i0005,i0006]
      z2002[i0005,i0006] = z0001
else:
  for i0005 in range(0, z2002_size[0], 1):
    i0006 = 0
    z0001 = z2002[i0005,i0006]
    for i0008 in range(0, z2002_size[1], 1):
      if i0006+z2002_size[1]//2+1 >= z2002_size[1]:
        i0007 = i0006+z2002_size[1]//2+1-z2002_size[1]
      else:
        i0007 = i0006+z2002_size[1]//2+1
      z2002[i0005,i0006] = z2002[i0005,i0007]
      i0006 = i0007
    z2002[i0005,i0006+z2002_size[1]//2+1-1] = z0001
if divmod(z2002_size[0],2) == 0:
  for i0005 in range(0, z2002_size[1], 1):
    for i0006 in range(0, z2002_size[0]//2, 1):
      z0001 = z2002[i0006+z2002_size[0]//2,i0005]
      z2002[i0006+z2002_size[0]//2,i0005] = z2002[i0006,i0005]
      z2002[i0006,i0005] = z0001
else:
  for i0005 in range(0, z2002_size[1], 1):
    i0006 = 0
    z0001 = z2002[i0006,i0005]
    for i0008 in range(0, z2002_size[0], 1):
      if i0006+z2002_size[0]//2+1 >= z2002_size[0]:
        i0007 = i0006+z2002_size[0]//2+1-z2002_size[0]
      else:
        i0007 = i0006+z2002_size[0]//2+1
      z2002[i0006,i0005] = z2002[i0007,i0005]
      i0006 = i0007
    z2002[i0006+z2002_size[0]//2+1-1,i0005] = z0001
z2002_empty[:] = z2002[:]
#FFTを実行
z2002 = ftplan2()
if divmod(z2002_size[1],2) == 0:
  for i0005 in range(0, z2002_size[0], 1):
    for i0006 in range(0, z2002_size[1]//2, 1):
      z0001 = z2002[i0005,i0006+z2002_size[1]//2]
      z2002[i0005,i0006+z2002_size[1]//2] = z2002[i0005,i0006]
      z2002[i0005,i0006] = z0001
else:
  for i0005 in range(0, z2002_size[0], 1):
    i0006 = 0
    z0001 = z2002[i0005,i0006]
    for i0008 in range(0, z2002_size[1], 1):
      if i0006+z2002_size[1]//2+1 >= z2002_size[1]:
        i0007 = i0006+z2002_size[1]//2+1-z2002_size[1]
      else:
        i0007 = i0006+z2002_size[1]//2+1
      z2002[i0005,i0006] = z2002[i0005,i0007]
      i0006 = i0007
    z2002[i0005,i0006+z2002_size[1]//2+1-1] = z0001
if divmod(z2002_size[0],2) == 0:
  for i0005 in range(0, z2002_size[1], 1):
    for i0006 in range(0, z2002_size[0]//2, 1):
      z0001 = z2002[i0006+z2002_size[0]//2,i0005]
      z2002[i0006+z2002_size[0]//2,i0005] = z2002[i0006,i0005]
      z2002[i0006,i0005] = z0001
else:
  for i0005 in range(0, z2002_size[1], 1):
    i0006 = 0
    z0001 = z2002[i0006,i0005]
    for i0008 in range(0, z2002_size[0], 1):
      if i0006+z2002_size[0]//2+1 >= z2002_size[0]:
        i0007 = i0006+z2002_size[0]//2+1-z2002_size[0]
      else:
        i0007 = i0006+z2002_size[0]//2+1
      z2002[i0006,i0005] = z2002[i0007,i0005]
      i0006 = i0007
    z2002[i0006+z2002_size[0]//2+1-1,i0005] = z0001
del ftplan2
#規格化
for i0005 in range(0, i0001, 1):
  for i0006 in range(0, i0002, 1):
    z2002[i0005,i0006] = z2002[i0005,i0006]/(i0001*i0002)
for i0001 in range(0, z2001_size[0], 1):
  for i0002 in range(0, z2001_size[1], 1):
    z2001[i0001,i0002] = z2001[i0001,i0002]*z2002[i0001,i0002].conjugate()
i0001 = z2001_size[0]
i0002 = z2001_size[1]
i0003 = z2001_size[0]//2
i0004 = z2001_size[1]//2
z2001_empty = pyfftw.empty_aligned(z2001.shape, dtype='complex128')
ftplan3 = pyfftw.builders.ifft2(z2001_empty)
if divmod(z2001_size[1],2) == 0:
  for i0005 in range(0, z2001_size[0], 1):
    for i0006 in range(0, z2001_size[1]//2, 1):
      z0001 = z2001[i0005,i0006+z2001_size[1]//2]
      z2001[i0005,i0006+z2001_size[1]//2] = z2001[i0005,i0006]
      z2001[i0005,i0006] = z0001
else:
  for i0005 in range(0, z2001_size[0], 1):
    i0006 = 0
    z0001 = z2001[i0005,i0006]
    for i0008 in range(0, z2001_size[1], 1):
      if i0006+z2001_size[1]//2 >= z2001_size[1]:
        i0007 = i0006+z2001_size[1]//2-z2001_size[1]
      else:
        i0007 = i0006+z2001_size[1]//2
      z2001[i0005,i0006] = z2001[i0005,i0007]
      i0006 = i0007
    z2001[i0005,i0006+z2001_size[1]//2+1] = z0001
if divmod(z2001_size[0],2) == 0:
  for i0005 in range(0, z2001_size[1], 1):
    for i0006 in range(0, z2001_size[0]//2, 1):
      z0001 = z2001[i0006+z2001_size[0]//2,i0005]
      z2001[i0006+z2001_size[0]//2,i0005] = z2001[i0006,i0005]
      z2001[i0006,i0005] = z0001
else:
  for i0005 in range(0, z2001_size[1], 1):
    i0006 = 0
    z0001 = z2001[i0006,i0005]
    for i0008 in range(0, z2001_size[0], 1):
      if i0006+z2001_size[0]//2 >= z2001_size[0]:
        i0007 = i0006+z2001_size[0]//2-z2001_size[0]
      else:
        i0007 = i0006+z2001_size[0]//2
      z2001[i0006,i0005] = z2001[i0007,i0005]
      i0006 = i0007
    z2001[i0006+z2001_size[0]//2+1,i0005] = z0001
z2001_empty[:] = z2001[:]
#FFTを実行
z2001 = ftplan3()
if divmod(z2001_size[1],2) == 0:
  for i0005 in range(0, z2001_size[0], 1):
    for i0006 in range(0, z2001_size[1]//2, 1):
      z0001 = z2001[i0005,i0006+z2001_size[1]//2]
      z2001[i0005,i0006+z2001_size[1]//2] = z2001[i0005,i0006]
      z2001[i0005,i0006] = z0001
else:
  for i0005 in range(0, z2001_size[0], 1):
    i0006 = 0
    z0001 = z2001[i0005,i0006]
    for i0008 in range(0, z2001_size[1], 1):
      if i0006+z2001_size[1]//2 >= z2001_size[1]:
        i0007 = i0006+z2001_size[1]//2-z2001_size[1]
      else:
        i0007 = i0006+z2001_size[1]//2
      z2001[i0005,i0006] = z2001[i0005,i0007]
      i0006 = i0007
    z2001[i0005,i0006+z2001_size[1]//2+1] = z0001
if divmod(z2001_size[0],2) == 0:
  for i0005 in range(0, z2001_size[1], 1):
    for i0006 in range(0, z2001_size[0]//2, 1):
      z0001 = z2001[i0006+z2001_size[0]//2,i0005]
      z2001[i0006+z2001_size[0]//2,i0005] = z2001[i0006,i0005]
      z2001[i0006,i0005] = z0001
else:
  for i0005 in range(0, z2001_size[1], 1):
    i0006 = 0
    z0001 = z2001[i0006,i0005]
    for i0008 in range(0, z2001_size[0], 1):
      if i0006+z2001_size[0]//2 >= z2001_size[0]:
        i0007 = i0006+z2001_size[0]//2-z2001_size[0]
      else:
        i0007 = i0006+z2001_size[0]//2
      z2001[i0006,i0005] = z2001[i0007,i0005]
      i0006 = i0007
    z2001[i0006+z2001_size[0]//2+1,i0005] = z0001
del ftplan3
t0003= "fg.dat"%()
f0002 = open(t0003,mode="w")
for i0001 in range(0, z2001_size[0], 1):
  for i0002 in range(0, z2001_size[1], 1):
    f0002.write("%8d\t%8d\t%27.12e\t%27.12e\n" %(i0001,i0002,(z2001[i0001,i0002]).real,(z2001[i0001,i0002]).imag))
f0002.close()
z2002_size[0] = -1
z2002_size[1] = -1
del z2002
z2001_size[0] = -1
z2001_size[1] = -1
del z2001
