/*=============================================================================================*/
/* Project name: test6_1 */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2026/03/01 1:56:49 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
int i0001;
int i0002;
int i0003;
double d0001;
double d0002;
double d0003;
double d0004;
double d0005;
double d0006;
double d0007;
double d0008;
double d0009;
double d0010;
double d0011;
double d0012;
double d0013;
double d0014;
double d0015;
double d0016;
double d0017;
double *d1001;
int d1001_size[1] = { -1 };
int main()
{
  d0001 = -10;
  d1001_size[0] = 10;
  d1001 = (double *)malloc(sizeof(double)*d1001_size[0]);
  for(i0001=0; i0001<=d1001_size[0]-1; i0001++)
  {
    d1001[i0001] = i0001;
  }
  for(i0001=0; i0001<=d1001_size[0]-1; i0001++)
  {
    /*代数微分*/
    d0007 = 0;
    for(i0002 = 0; i0002 <= 9; i0002++)
    {
      d0007 = d0007+i0002*i0002;
    }
    d0006 = d0007;
    d0008 = 0;
    for(i0002 = 0; i0002 <= 9; i0002++)
    {
      if(i0002 == i0001)
      {
        i0003 = 1;
      }
      else
      {
        i0003 = 0;
      }
      d0008 = d0008+i0002*i0002*i0003;
    }
    d0009 = 0;
    for(i0002 = 0; i0002 <= 9; i0002++)
    {
      d0009 = d0009;
    }
    d0010 = 0;
    for(i0002 = 0; i0002 <= 9; i0002++)
    {
      d0010 = d0010+i0002*i0002*d1001[i0002];
    }
    d0011 = 0;
    for(i0002 = 0; i0002 <= 9; i0002++)
    {
      d0011 = d0011;
    }
    d0004 = d0008/d0006+(d0009/d0006-d0010/pow(d0006,2))*d0011;
    /*数値微分*/
    d0013 = 0;
    for(i0002 = 0; i0002 <= 9; i0002++)
    {
      d0013 = d0013+i0002*i0002;
    }
    d0012 = d0013;
    d0014 = 0;
    for(i0002 = 0; i0002 <= 9; i0002++)
    {
      d0014 = d0014+i0002*i0002*d1001[i0002];
    }
    d0002 = d0014/d0012;
    d1001[i0001] = d1001[i0001]+1.0E-5;
    d0016 = 0;
    for(i0002 = 0; i0002 <= 9; i0002++)
    {
      d0016 = d0016+i0002*i0002;
    }
    d0015 = d0016;
    d0017 = 0;
    for(i0002 = 0; i0002 <= 9; i0002++)
    {
      d0017 = d0017+i0002*i0002*d1001[i0002];
    }
    d0003 = d0017/d0015;
    d1001[i0001] = d1001[i0001]-1.0E-5;
    printf("%8d%27.12e%27.12e\n",i0001,d0004,(d0003-d0002)/1.0E-5);
  }
  d1001_size[0] = -1;
  free(d1001);
  return 0;
}
